In [1]:
import pandas as pd
import numpy as np

In [2]:
df_culture = pd.read_csv('culture.csv')
df_sport = pd.read_csv('sport.csv')
df_legal = pd.read_csv('legal.csv')
df_polictics = pd.read_csv('politics_data.csv')

In [3]:
df_culture['label'] = 'Culture'
df_culture = df_culture.rename(columns={df_culture.columns[0]: 'text'})

df_sport['label'] = 'Sport'
df_sport = df_sport.rename(columns={df_sport.columns[0]: 'text'})

df_legal['label'] = 'Legal'
df_legal = df_legal.rename(columns={df_legal.columns[0]: 'text'})

df_polictics['label'] = 'Politics'
df_polictics = df_polictics.rename(columns={df_polictics.columns[0]: 'text'})

In [4]:
final_data = pd.concat([df_culture, df_sport, df_polictics], ignore_index=True)

In [5]:
final_data = final_data[['label', 'text']]

In [6]:
final_data.to_csv('final_data.csv', index=False, encoding='utf-8-sig')

In [7]:
final_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 807 entries, 0 to 806
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   label   807 non-null    str
 1   text    807 non-null    str
dtypes: str(2)
memory usage: 12.7 KB

In [9]:
final_data.head(5)

                                             Content Sport Politick
0  The Second Khachaturian International Youth Co...   NaN      NaN
1  Changing Sound of Armenian Jazz   Soprano Bayr...   NaN      NaN
2  Eleonora Gotti From psychologist to abstract e...   NaN      NaN
3  Connecting to Heritage and Reaffirming Passion...   NaN      NaN
4  I present the Armenian kanun in both classical...   NaN      NaN

In [11]:
final_data['Politick'].isna().sum()

np.int64(303)

In [8]:
df_culture['label'] = 'Culture'
df_culture = df_culture.rename(columns={df_culture.columns[0]: 'text'})

df_sport['label'] = 'Sport'
df_sport = df_sport.rename(columns={df_sport.columns[0]: 'text'})

df_legal['label'] = 'Legal'
df_legal = df_legal.rename(columns={df_legal.columns[0]: 'text'})

df_polictics['label'] = 'Politics'
df_polictics = df_polictics.rename(columns={df_polictics.columns[0]: 'text'})

final_data = pd.concat([df_culture, df_sport, df_polictics], ignore_index=True)

final_data = final_data[['label', 'text']]

final_data.to_csv('final_dataset.csv', index=False, encoding='utf-8-sig')

print("Dataset-ը պատրաստ է: Պահպանվեց 'final_dataset.csv' անունով:")

Dataset-ը պատրաստ է: Պահպանվեց 'final_dataset.csv' անունով:

In [5]:
df = pd.read_csv('final_dataset.csv')

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 807 entries, 0 to 806
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   label   807 non-null    str
 1   text    807 non-null    str
dtypes: str(2)
memory usage: 12.7 KB

In [7]:
df.head()

     label                                               text
0  Culture  The Second Khachaturian International Youth Co...
1  Culture  Changing Sound of Armenian Jazz   Soprano Bayr...
2  Culture  Eleonora Gotti From psychologist to abstract e...
3  Culture  Connecting to Heritage and Reaffirming Passion...
4  Culture  I present the Armenian kanun in both classical...